### ISSUE TITLE
Keeps loading.. doesn't ever finish 

### ISSUE THREAD

**Issue by laggingreflex** [thomasandersen/gfycat-companion-for-firefox#7]
The progress bar just keeps loading again and again and nothing else happens.

![](http://i.imgur.com/h7UheY1.png)

![](http://i.imgur.com/QmkU39c.png)

gfycats natively work fine though..

[![](http://i.imgur.com/IkfA92y.png)](http://reddit.com/r/gfycats/comments/1x2h38/cracking_an_egg_underwater)

Any idea what might be the issue?

**Comment by thomasandersen** [comment]
Does this always happen?

Could you please try this video? http://mr-andersen.no/gfcycat-companion-test/issues/7.html

**Comment by laggingreflex** [comment]
I've only just installed the addon after updating my firefox to 28 (from 23), but since then, yes, always. 

[That page is blank for me](http://i.imgur.com/7bknaMJ.png)

**Comment by thomasandersen** [comment]
This could be a Windows/Firefox issue
What about this page? http://www.w3.org/2010/05/video/mediaevents.html

If you are familiar with DevTools you can try to inspect the loaded video file
 (See: Tools -> Web Developer -> Network)
I believe version 28/DevTools has a bug regarding partially/cached resources so you need to clear the browser cache in order to inspect the file properly.
The file should be named trailer.webm
When selecting the file in the request list you should see a Headers tab in the side panel.
In the Headers tab look for Response Headers. In the Response headers block there should be a header named Content-Type. The value to expect is video/webm.

and finally, what does this page tell you?
https://www.youtube.com/html5 

See the "What does this browser support?" section.

**Comment by laggingreflex** [comment]
It's video/mp4 not video/webm. Any good? 

![](http://i.imgur.com/OnitwUi.png)

And youtube tells me this:
![](http://i.imgur.com/KxDu0Dn.png)

BTW, I'm on windows 8 64 bit.

**Comment by thomasandersen** [comment]
> It's video/mp4 not video/webm. Any good? 

Yes, that is good information. Seems like the system prefer mp4 over webm. A bit strange since the Mozilla docs does not says anything about this.

Anyway, I have added support for mp4 now. Can you please test it by download/install from the link below[1].
Please note that this is beta version 3. The 'pre' component to the version number has been added so when beta 3 blank or higher is released on addons.mozilla.org this build will get the update too.

[1] http://mr-andersen.no/gfycat-companion/gfycat-companion-for-firefox-0.4b3pre.xpi

Please let me know how it works.

**Comment by laggingreflex** [comment]
[It works!](http://i.imgur.com/pqe4kZk.png) yay! Thanks a bunch

**Comment by thomasandersen** [comment]
> It works! yay! Thanks a bunch
> Great! Thank you for providing good information.

**Comment by THERAILMCCOY** [comment]
I'm still getting this issue, even using the 0.4b3pre version linked above.  Using Firefox 30 and Windows 7 64 bit.  Here are images answering the questions you asked laggingreflex.

![w3org](https://cloud.githubusercontent.com/assets/4952323/3438742/7ca587ae-00d0-11e4-843c-1f6a8446697f.JPG)

![youtube](https://cloud.githubusercontent.com/assets/4952323/3438744/7efb2a90-00d0-11e4-8119-b36b4ebb9823.JPG)
